from .i_paciente_repository import IPacienteRepository
from .i_cita_repository import ICitaRepository
from .i_personalMedico_repository import IPersonalMedicoRepository
from .i_cirugia_repository import ICirugiaRepository
from .i_medicamento_repository import IMedicamentoRepository
from .i_proveedor_repository import IProveedorRepository
