from .paciente import Paciente
from .cita import Cita
from .personalMedico import PersonalMedico
from .habitacion import Habitacion
from .cirugia import Cirugia
from .formula import Formula
from .medicamento import Medicamento
from .proveedor import Proveedor
from .historialMedico import HistorialMedico
from .usuario import Usuario
